### ISSUE TITLE
on mac, stuck on select language

### ISSUE THREAD

**Issue by robertchen** [tranphuquy19/ubuntu-desktop-packer#1]
my env:
$ packer version
Packer v1.8.4

MAC, Ventura 13.0.1; virtualbox 7.0.4

$packer build -only=virtualbox-iso -var-file=ubuntu2204-desktop.json ubuntu.json

It is stuck here:
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/1059160/207388912-3039f356-92a8-47c5-88dd-238e4903922c.png">

Please help , thx for great work

**Comment by tranphuquy19** [comment]
Please try `packer build -only=virtualbox-iso -var-file=ubuntu2204-desktop.json ubuntu2204.json`. It worked for me on the ubuntu machine and Windows also.

**Comment by robertchen** [comment]
thanks, in the Windows seems works, but after the box was created, when I do vagrant up, I got this error:

bash-4.4$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'ubuntu-22.04-desktop'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: virtualbox_default_1671120171701_81882
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...

**Comment by robertchen** [comment]
by the way, the stuck on select language issue was because of virtualbox 7.0.4 version. Seems virtualbox 6.1.40 does not have this issue.
